### ISSUE TITLE
Is there a CF-compatible release for this mod?

### ISSUE THREAD

**Issue by katubug** [JarHax/ModJam-5#4]
I understand that it seems to be no longer maintained. However, I really liked the idea of it and I'd rather like to try it out. Do you have any full releases on gh that I could download, or would I have to compile my own? And in either case, would either way be an issue if I wanted to include the mod in a CF modpack?

I guess another valid question is whether or not the mod is stable enough for modpack inclusion, haha.

Thank you very much for your time!

**Comment by Darkhax** [comment]
Thanks for your interest in the project. The only release of the mod available is the [1.8.0 modjam release](http://i.blamejared.com/ModJam5-1.12.2-1.8.0.jar). We have plans to come back to the mod eventually but haven't had the time. The mod is stable enough to be used in modpacks however it is not compatible with CurseForge's public modpack policy. In the future we will be giving the mod a CurseForge release which will work with their modpacks.

**Comment by katubug** [comment]
Thanks very much for your response! In that case, I'll follow the project so I don't miss any updates. Thanks for all your fantastic content and your thorough answer. :)
